#+TITLE: Discrete Geometry 1
#+LATEX_HEADER: \usepackage[left=2cm, right=2cm, bottom=2cm, top=2cm]{geometry}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \def\R{\mathbb{R}}
#+LATEX_HEADER: \def\Z{\mathbb{Z}}
#+LATEX_HEADER: \def\pos{\operatorname{pos}}
#+LATEX_HEADER: \def\conv{\operatorname{Conv}}

* Lecture 2 <2018-10-17 Wed>

** Definitions
*** Positive half
*** Affine hyperplane
*** (Question) What is the space of all oriented hyperplanes of $\R^n$
*** Definition of pos?
** Radon's theorem
   Three cases

   - If the size of M is greater than or equal to n+2, there is a radon partiiton
   - If the size of $M$ is greater than or equal to $n+1$, $0$ is an appex of
     $M$ and $0\neq M$. or $|M| \ge n+2$.

     then there is a partition of $M_1$ and $M_2$ of $M$ such that $\pos M_1
     \cap pos M_2 \neq \emptyset$.
   - partition is unique if and only i f
     - $|M| = n+2$ and $n+1$ points of m$ are affinely dependent.
     - $|M| = n+1$ and no $n$ vectors of $M$ are linearly independent.
** Definitions
*** Radon partition
    A partition $M_1, M_2$ such that $\conv M_1 \cap conv M_2 \neq \emptyset$ is called a *Radon partition*.
** Proof
*** Part 1
    Size of $M$ greater than $n+2$. Take $x_1, \cdots, x_{n+2}$ pairwise disjoint points from $M.

    Then $x_1, \cdots x_{n+2}$ are affinely dependent, meaning that that you can
    choose scalars, real such that $\sum \lambda_i x_i = 0$.

    We can assume that for some $1 \le j \le n+1$ holds

    $\lambda_1 >0, \cdots, \lambda_i >0$ and $\lambda_{i+1} \le 0, \cdots, \lambda{n+2} \le 0$.

    $\lambda = \lambda_1 + \cdots + \lambda_j = -(\lambda_{i+1} + \cdots + \lambda_{n+2}$.

    $X=\frac1\lambda (\lambda_1 x_1 + \cdots \lambda_j x_j)$ a convex
    combination $\in \conv\{x_1, \cdots, x_j\}$.

    $$\frac{1}{\lambda}(\lambda_1x_1 + \cdots + \lambda_{n+2}x_{n+2}) = 0.$$


    $$X= \frac{1}{\lambda}(\lambda_1x_1 + \cdots + \lambda_{j}x_{j})  = -\frac{1}{\lambda}(\lambda_jx_j + \cdots + \lambda_{n+2}x_{n+2}) = 0.$$

    a convex combination.

    Thus $X$ is inside both the intersection.
*** Part 2

    $\pos M$ is a cone with appex ... 

    *A drawing*

    For every point $x_i \in M$, there is $\alpha_i > 0$, such that $\alpha_ix_i
    \in H'$,,

    blah blah.

    Keyword: matroids.
*** Part 3
    I didn't type.

    (A part.) A partition is unique.

    Let $|M| = n+2$ and $x_1, \cdots, x_{n+2}$ are affinely dependent implies
    $x_1, \cdots x_{n+1}$ (dropped one point) have to be on a affine hyperplane.
    Then by Radon's theorem, there is a partition $M_1'$ and $M_2'$ such that
    the convex hulls of these intersect. But then we can add the element
    $x_{n+2}$ to $M_1'$ or $M_2'$ to form two different partitions. Thus we have
    two Radon partitions of $M$ and thus this is a contradiction.

    Case for $|M| \ge n+3$. Let $\tilde{M} \subset M$ and $|\tilde{M}| = n+2$
    such that $M-\tilde M \neq \emptyset$. Then $\tilde M_1, \tilde M_2$ is a
    partition of $\tilde M$.

    $\conv \tilde M_1 \cap \conv \tilde M_2 \neq \emptyset$.

    $$\tilde M_1 \cap (M-\tilde M), \tilde M_2$$

    and $$\tilde M_2 \cap (M-\tilde M)$$ forms two different radon partitions and
    again, we have a contradiction.
** Questions 
*** About affine maps
    We have an arbitrary affine map between a simplex (n+1 dimensional) and
    $\R^n$. implies, there exist faces of the simpleces such that the faces do
    not intersect, but the images of the faces will intersect. Apparently this
    follows from the Radon's theorem. A different formulation of Radon's theorem

    $a\colon T_{n+1} \rightarrow \R^n$

    *Question*: Replace the affine map by a continuous map and is it still true? [fn:1]

    *Question*: How many points in $M \subset \R^d$ you should have to generate
    that for $n\ge 2$, there is a partition $M_1, \cdots, M_r$ of $M$ such that
    the intersection of the convex hulls of $M_i$ are non-empty. 

    *Question*: More points, minimal number of points?

* Footnotes

[fn:1] Wikipedia article about Radon'n theorem says that this is true. Crazy.
    

